Update documents for sda/sdb reversal and other
nvi-inc/fsl11 pull request #10
Opened 2022-09-25 19:43 UTC by wehimwich

For merging after #8, still a work in progress.

Rephrase all operations in terms of primary/secondary disks only, except for installation of grub on the secondary disk.
Use rotation_shutdown in all cases where it is applicable. Change recoverable testing procedure to have subsections for easier referencing with links.
Fix links to installation.adoc in raid.adoc.
Make other minor wording and formatting improvements.

2022-09-27 15:16 UTC, jfhquick requested changes
Although subsections should make sense separately, one has to be careful of overdoing the repetition between sections --  "but may be a little slow" is another monotonous refrain.

2022-09-27 15:16 UTC, jfhquick commented on installation.adoc
> +=== Install GRUB to the second disk (if available)
So this procedure is dangerous as the intervening reboot could have reversed the sda/sdb assignment, whereupon you will hose GRUB instead.

2022-09-27 15:16 UTC, jfhquick commented on installation.adoc
> +you are not using that procedure, will need to use your own recovery
...procedure, you will need ...

2022-09-27 15:16 UTC, jfhquick commented on installation.adoc
> +the <<raid.adoc#,Raid Notes for FSL11>> document
This change is wrong - the full stop should be there.

2022-09-27 15:16 UTC, jfhquick commented on raid.adoc
> +11 Installation Guide>> document). The scripts have had been updated
... scripts have been updated ... (no had)

2022-09-27 15:16 UTC, jfhquick commented on raid.adoc
> +prevent shutting down: (i) if the FS is running, you should terminate
This a duplication.  I'd suggest that this is handled once where you first mention the use of the script and removed from the current locations.

2022-09-27 15:16 UTC, jfhquick commented on raid.adoc
> +down _only_ if the RAID is synced. There are three errors that can
And another duplicate.

2022-09-27 15:16 UTC, jfhquick commented on raid.adoc
> +down _only_ if the RAID is synced. There are three errors that can
And another

2022-09-27 18:58 UTC, wehimwich commented on installation.adoc
> +=== Install GRUB to the second disk (if available)
Right. I believe the next change is to only setup with one disk. That is coming ...

2022-09-27 19:21 UTC, wehimwich commented
Thanks for all the corrections.

> Although subsections should make sense separately, one has to be careful of overdoing the repetition between sections -- "but may be a little slow" is another monotonous refrain.

I am not opposed to what you are saying. OTOH, I don't think these sections are likely to be read one after another. For the reader just using a procedure (a reputed user), it may be more important that they be self-contained. Another option for the _rotation_shutdown_  disclaimer might to be only have it in the rotation procedure and link to it from the others. "slow" might only be in the rotation procedure, the most likely one to be used. Still thinking about this ...

HTML of the new docs are available at [DRAFT Installation](https://nvi-inc.github.io/fsl11/draft_installation.html) and [DRAFT raid](https://nvi-inc.github.io/fsl11/draft_raid.html).

2022-09-27 19:31 UTC, jfhquick commented
On Tue, September 27, 2022 9:21 pm, Ed Himwich wrote:
> Another option for the _rotation_shutdown_  disclaimer might to be only have
> it in the rotation procedure and link to it from the others. "slow" might only
> be in the rotation procedure, the most likely one to be used. Still thinking
> about this ...

Perhaps every mentioned use of a procedure should be a link to the subsection
that describes it in gory detail.

2022-09-29 13:34 UTC, wehimwich commented
I have removed all but one redundancy. The full explanation is only given for the disk rotation procedure. That is the one that will be used the most and the part of the document that most users will read. Other procedures rely on familiarity. There are two cases where the same deferred follow-up action is needed. That was duplicated to make it clear that it applied in those cases.

I also touched the `-f` clause of _recover_raid_.

2022-10-04 17:52 UTC, jfhquick approved these changes

2022-10-05 17:03 UTC, merged