Rotation cleanup
nvi-inc/fsl11 pull request #14
Opened 2024-01-10 23:59 UTC by wehimwich

This PR tries to cleanup a couple small issues:

1. In _rotation_shutdown_, the prompt for confirming shutting down was moved to the start of the script. The goal being to avoid having a potential long delay (if the user doesn't respond to the prompt quicky) between verifying that shutting down is sae and the actual shutdown.
2. In _refresh_secondary_, the age of the secondary disk is checked. If it is less than three hours old, the refresh is aborted. The idea is catch if the operator accidentally inserted the _new_ shelf disk by mistake. Using _blank_secondary_ is a way for an expert to override this check.
 
I am not sure what the best age limit is in _refresh_secondary_. If it is too short, the operator can keep trying to run the script (without thinking about it) until it succeeds. If it is too long, it might interfere with some tasks like doing another rotation to get the disks in the correct cyclical order. OTOH, an operator would probably not be doing such tasks. This might argue for a larger limit, maybe a day or even a week or two (assuming rotations are done monthly). Also a longer limit would allow more time for an expert to look into what went wrong. For now I left it at three hours. A refresh of a 2 TB disk takes a bit longer than this, so after the refresh the operator could do another rotation without special measures. It is long enough that the check won't be overridden unless the operator is really determined. Anyway, it shouldn't happen by accident.

These two commit are disjoint. Unless the branch gets more complicated, it can probably be FF'd onto _main_ when it is ready.

A question is whether these (and other accumulated changes) are enough to have a minor release. In any event, a user could update by pulling _main_ and running _RAID/install_tools_.

2024-01-11 20:34 UTC, wehimwich commented
I stand corrected. A 2 TB disk seems to take about4.5 hours on an unloaded system. Unless anyone is buying faster (more expensive) or smaller disks, maybe we could bump the age limit up to four hours.

2024-01-12 10:03 UTC, wehimwich commented
I updated the error messages for the age limit to be in the style of the other checks, which I think are appropriately "just the facts." I also went for four hours, which is still tentative.

Since this is phrased as two fixups, FF (or "rebase and merge") won't give the cleanest result now.

2024-01-13 17:18 UTC, wehimwich commented
This disallows the `-A` (and `-n`) options of _refresh_secondary_ for AUID users to make it safer.  Is `-n` suppose to be a hidden option? We could allow it as well (and/or add it to the _refresh_secondary_ `-h` option).

2024-01-16 20:34 UTC, jfhquick reviewed
Sure;y it would be cleaner to use a (30s?) countdown timer after the checks have been down which would instead allow cancellation via Ctrl-C?  Then it could only be shown when you are ready to shutdown.

2024-01-16 20:45 UTC, jfhquick requested changes
This last commit is completely orthogonal to the other changes (which don't relate to AUID usage) ie. doesn't belong in this PR.

2024-01-17 14:02 UTC, wehimwich commented
> This last commit is completely orthogonal to the other changes (which don't relate to AUID usage) ie. doesn't belong in this PR.

True enough, but it is related to the topic. It does stray into AUID issues, which is less FSL11 per se. My thinking is that this PR is just a way to have a conversation about these loosely related changes. Once the fix-ups are applied, we would be left with three commits that could either be FF'd on to _main_ or added with a merge commit. The choice between the two is a matter of taste.

2024-01-17 14:26 UTC, wehimwich commented
> Sure;y it would be cleaner to use a (30s?) countdown timer after the checks have been down which would instead allow cancellation via Ctrl-C? Then it could only be shown when you are ready to shutdown.

If something is at stake,  I prefer positive confirmation, à la your _blank_secondary_. However, my thinking on this has changed (my gears turn slowly and not the most smoothly, don't get me started about those pesky left-side diodes). _rotation_shutdown_ seems no more dangerous than `shutdown -h now`. In addition to requiring the correct RAID state, _rotation_shutdown_ will not allow a shutdown if the FS is running unless the user overrides that check with `-F` (a possibly valid operator decision).  So at this point, I am inclined to withdraw the shutdown confirmation prompt entirely (and as is the case already, not block `-F` for AUID).

2024-01-19 15:29 UTC, wehimwich commented
The _main_ branch was updated to remove the confirmation prompt in _rotation_shutdown_ and to only allow either no options or one of `-h` or `-p` with _refresh_secondary_ for AUID users. That reduced this PR to one commit for checking the age of the disk being refreshed.

 I followed your suggestion in email to reword the message to call it a `SANITY CHECK` instead of an `ERROR` and to increase the age limit to one day.

`FF`ing the commit onto _main_ (`Rebase and merge` on _github_) will prevent the now inaccurate branch name from living on in the history.

2024-01-19 20:21 UTC, jfhquick commented
Looks good to go.

2024-01-19 20:22 UTC, merged

2024-01-19 20:23 UTC, jfhquick reviewed
Looks good